### ISSUE TITLE
broadcast messages

### ISSUE THREAD

**Issue by Schrims** [tegioz/chat#10]
hi how do you broadcast messages to all users?

---

Broadcast API
Send messages to all connected users:
Content-Type: application/json
POST /api/broadcast/
{"msg": "Hello!"}

---

Can you tell me how to execute this command?

**Comment by tegioz** [comment]
Hi @Schrims 

Something like this should work (I haven't tested it):

```
curl -H 'Content-Type: application/json' -X POST -d '{"msg": "Hello!"}' http://localhost:8888/api/broadcast/
```

**Comment by tegioz** [comment]
Another option would be to use a browser extension (like Postman -there are plenty of options-) to talk to the API from your browser.

**Comment by Schrims** [comment]
Thanks, i will give it a try!

**Comment by Schrims** [comment]
if i execute your command - i got the following error message
but i will take a look at it!

TypeError: sanitize is not a function
    at sanitizeMessage (/Workspace/chat/chatServer.js:64:32)
    at callbacks (/Workspace/chat/node_modules/express/lib/router/index.js:164:37)
    at requireAuthentication (/Workspace/chat/chatServer.js:58:5)
    at callbacks (/Workspace/chat/node_modules/express/lib/router/index.js:164:37)
    at param (/Workspace/chat/node_modules/express/lib/router/index.js:138:11)
    at pass (/Workspace/chat/node_modules/express/lib/router/index.js:145:5)
    at Router._dispatch (/Workspace/chat/node_modules/express/lib/router/index.js:173:5)
    at Object.router (/Workspace/chat/node_modules/express/lib/router/index.js:33:10)
    at next (/Workspace/chat/node_modules/connect/lib/proto.js:190:15)
    at Object.staticMiddleware [as handle] (/Workspace/chat/node_modules/connect/lib/middleware/static.js:55

**Comment by cynthia-sg** [comment]
Le echo un ojo luego Muak 

Ni idea de que es esto Muakk

**Comment by tegioz** [comment]
Hi @Schrims 

Just pushed a couple of changes that should fix the issues you have. This project is quite old and some updates in dependencies have broken it over time (will fix the versions soon though). I hadn't touch it in a while, was fun :) There may be more things broken, so if you find more issues and want to play with it a bit pull requests are welcome.

**Comment by Schrims** [comment]
Thanks @tegioz for your support!
It's now working with your changes and the given command.

I'll play with it and keep you informed.

THANKS!
